"""Add employee punch identifiers

Revision ID: aa966a094805
Revises: 1cbb0375d285
Create Date: 2026-03-18 20:20:17.300990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa966a094805'
down_revision = '1cbb0375d285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nfc_uid', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_employees_badge_id', ['badge_id'])
        batch_op.create_unique_constraint('uq_employees_nfc_uid', ['nfc_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employees_nfc_uid', type_='unique')
        batch_op.drop_constraint('uq_employees_badge_id', type_='unique')
        batch_op.drop_column('nfc_uid')
        batch_op.drop_column('badge_id')

    # ### end Alembic commands ###
